github act

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,9 +34,23 @@ jobs:
           bun run build
           bun run export
 
+
+      - name: Build and export the project
+        run: |
+          if [ ! -d "out" ]; then
+            echo "Error: out directory does not exist."
+            exit 1
+          fi
+
       - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GH_TOKEN }}
-          publish_dir: ./out
-          destination_dir: .
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          git clone --branch=main https://github.com/IshuSinghSE/IshuSinghSE.github.io.git gh-pages
+          cp -r out/* gh-pages/
+          cd gh-pages
+          git add .
+          git commit -m 'Deploy Next.js app'
+          git push origin main
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
